// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'agency_order_detail_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$AgencyOrderDetailResponseImpl _$$AgencyOrderDetailResponseImplFromJson(
        Map<String, dynamic> json) =>
    _$AgencyOrderDetailResponseImpl(
      id: json['id'] as String?,
      orderCode: json['orderCode'] as String?,
      orderMethod: json['orderMethod'] as int?,
      userId: json['userId'] as String?,
      status: json['status'] as int?,
      paymentStatus: json['paymentStatus'] as int?,
      payment: (json['payment'] as num?)?.toDouble(),
      userName: json['userName'] as String?,
      phoneNumber: json['phoneNumber'] as String?,
      address: json['address'] as String?,
      email: json['email'] as String?,
      district: json['district'] as String?,
      province: json['province'] as String?,
      commune: json['commune'] as String?,
      note: json['note'] as String?,
      image: json['image'],
      paymentMethod: json['paymentMethod'] as int?,
      createdDate: json['createdDate'] as String?,
      lastModifiedDate: json['lastModifiedDate'],
      transportFee: json['transportFee'],
      discountCode: json['discountCode'],
      fullName: json['fullName'] as String?,
      referralName: json['referralName'] as String?,
      productOrders: (json['productOrders'] as List<dynamic>?)
          ?.map((e) => ProductOrder.fromJson(e as Map<String, dynamic>))
          .toList(),
      transportId: json['transportId'],
      transportMethod: json['transportMethod'] as int?,
      warehouseId: json['warehouseId'],
      warehouseName: json['warehouseName'],
      warehouseAddress: json['warehouseAddress'],
      receiverName: json['receiverName'],
      receiverPhoneNumber: json['receiverPhoneNumber'],
      receiverAddress: json['receiverAddress'],
      receiverEmail: json['receiverEmail'],
      receiverDistrict: json['receiverDistrict'],
      receiverProvince: json['receiverProvince'],
      receiverCommune: json['receiverCommune'],
      receiverId: json['receiverId'],
      discountAmount: json['discountAmount'],
      discountCodeInfo: json['discountCodeInfo'],
      agency: json['agency'],
      isUpdate: json['isUpdate'] as bool?,
      weight: json['weight'] as int?,
      length: json['length'] as int?,
      width: json['width'] as int?,
      height: json['height'] as int?,
    );

Map<String, dynamic> _$$AgencyOrderDetailResponseImplToJson(
        _$AgencyOrderDetailResponseImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'orderCode': instance.orderCode,
      'orderMethod': instance.orderMethod,
      'userId': instance.userId,
      'status': instance.status,
      'paymentStatus': instance.paymentStatus,
      'payment': instance.payment,
      'userName': instance.userName,
      'phoneNumber': instance.phoneNumber,
      'address': instance.address,
      'email': instance.email,
      'district': instance.district,
      'province': instance.province,
      'commune': instance.commune,
      'note': instance.note,
      'image': instance.image,
      'paymentMethod': instance.paymentMethod,
      'createdDate': instance.createdDate,
      'lastModifiedDate': instance.lastModifiedDate,
      'transportFee': instance.transportFee,
      'discountCode': instance.discountCode,
      'fullName': instance.fullName,
      'referralName': instance.referralName,
      'productOrders': instance.productOrders?.map((e) => e.toJson()).toList(),
      'transportId': instance.transportId,
      'transportMethod': instance.transportMethod,
      'warehouseId': instance.warehouseId,
      'warehouseName': instance.warehouseName,
      'warehouseAddress': instance.warehouseAddress,
      'receiverName': instance.receiverName,
      'receiverPhoneNumber': instance.receiverPhoneNumber,
      'receiverAddress': instance.receiverAddress,
      'receiverEmail': instance.receiverEmail,
      'receiverDistrict': instance.receiverDistrict,
      'receiverProvince': instance.receiverProvince,
      'receiverCommune': instance.receiverCommune,
      'receiverId': instance.receiverId,
      'discountAmount': instance.discountAmount,
      'discountCodeInfo': instance.discountCodeInfo,
      'agency': instance.agency,
      'isUpdate': instance.isUpdate,
      'weight': instance.weight,
      'length': instance.length,
      'width': instance.width,
      'height': instance.height,
    };
